language: android
android:
  components:
    - android-26
    - build-tools-26.0.2
    - build-tools-27.0.1
    - extra-google-m2repository
    - extra-android-support
    - extra-android-m2repository


script: ./gradlew assemble test check